spring:
  profiles:
    active: window-dev
---
server:
  port: 8081

logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: window-dev
  application:
    name: flex-employee
  data:
    mongodb:
      uri: mongodb://localhost:27017/flex
   
---

server:
  port: 8080
              
logging:
  level:
    yongs:
      temp: DEBUG
    
spring:
  profiles: docker-dev
  application:
    name: flex-employee
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:27017/${MONGO_DATABASE}
