spring:
  profiles:
    active: window-dev
---
server:
  port: 8081

logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: window-dev
  application:
    name: flex-employee
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flex
   
---

server:
  port: 8080
              
logging:
  level:
    yongs:
      temp: DEBUG
    
spring:
  profiles: docker-dev
  application:
    name: flex-employee
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}   
